{% set name = "binda" %}
{% set version = "1.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/binda-{{ version }}.tar.gz
  sha256: 86c1eef6c48ee520f244aac2ebcc8cd62f2e0c0ec97d88b9c1a5ea8719c40e82

build:
  entry_points:
    - hatch = hatch.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.6
    - pandas
    - numpy

test:
  imports:
    - binda
  commands:
    - pip check
    - hatch --help
  requires:
    - pip

about:
  summary: Read and write binary data using Pandas
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jking-ca
